# Generated by Django 5.0.6 on 2024-05-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('minor', 'Minor'), ('mediocre', 'Mediocre'), ('severe', 'Severe')], max_length=255, null=True)),
            ],
        ),
    ]
