# Generated by Django 5.0.6 on 2024-05-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.AddField(
            model_name='report',
            name='timestamp_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='timestamp_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
