# Generated by Django 5.0.6 on 2024-05-10 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_report_location_report_timestamp_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='confidence',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
