# Generated by Django 5.0.6 on 2024-05-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_report_video_filename_alter_report_confidence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='video_filename',
            new_name='video',
        ),
    ]
