# Generated by Django 5.0.6 on 2024-05-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_video_filename_report_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='timestamp_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='timestamp_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
